### ISSUE TITLE
Install postgres configuration

### ISSUE THREAD

**Issue by loujaybee** [openupthecloud/open-cloud-dev-box#14]
1. Copy an existing installation file https://github.com/openupthecloud/open-cloud-dev-box/blob/main/install-aws-cli.sh
    1. Use https://github.com/openupthecloud/open-cloud-dev-box/pull/7/files for inspiration if needed
1. Add installation steps for `pg` CLI (https://www.postgresql.org/download/linux/ubuntu/)
1. Ensure pg is running by starting new workspace + running `postgres -V`
1. Raise a pull request

**Comment by awscloudgirl** [comment]
ok thank you :)
