### ISSUE TITLE
Add VS Code extensions to configuration (e.g. Python)

### ISSUE THREAD

**Issue by loujaybee** [openupthecloud/open-cloud-dev-box#17]
1. Update `.gitpod.yml` with relevant extensions https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions

For example, you'll need to add the following configuration to `.gitpod.yml`

```
vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss@0.6.11
```

You'll need to research good extensions to add, for example: 

1. https://open-vsx.org/extension/ms-python/python
2. https://aws.amazon.com/visualstudiocode/
3. https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres
4. https://marketplace.visualstudio.com/items?itemName=hariscodes.vscode-dynamodb

You can validate whether this works, by creating a new workspace with new configuration, and checking that the VS Code extensions are installed

![image](https://user-images.githubusercontent.com/5528307/211167279-ad2d060a-be74-4b55-b4aa-d5b799535186.png)
_Example installed extensions in VS Code_

**Comment by yaya2devops** [comment]
I take that
